markdown: rdiscount
pygments: true
permalink: /:year/:month/:title
paginate: 5
relative_permalinks: false
exclude: [prepros.json, config.rb, typo/]
name: kleinfreund
description: Moonbase of Philipp Rudloff. Doing Web Development and Design. Things and stuff.
url: http://kleinfreund.de
