markdown: rdiscount
destination: "C:/Users/Philipp/_dev/github/kleinfreund.github.io"
pygments: true
permalink: /:categories/:year/:month/:title
paginate: 5
relative_permalinks: false
include:
- .nojekyll
exclude: [prepros.json, config.rb, assets/fonts]

name: kleinfreund
description: Mondbasis von Philipp Rudloff. Mache Webentwicklung und -design. Dinge und Sachen auch.
url: http://kleinfreund.de

default_locale: de
authorized_locales: [de, en]

locales:
  de:
    url: "/de/"
    language: "de"
    nav:
    - text: "Blog"
      url:  "/de/"
      class: "site-nav__item--blog"
    - text: "Portfolio"
      url:  "/de/portfolio/"
      class: "site-nav__item--portfolio"
    - text: "Profil"
      url:  "/de/profil/"
      class: "site-nav__item--profile"
    description: "Mondbasis von Philipp Rudloff. Mache Webentwicklung und -design. Dinge und Sachen auch."
    footer: "Mondbasis von <a href='http://twitter.com/kleinfreund'>Philipp Rudloff</a>. Gehostet auf <a href='http://github.com/kleinfreund/kleinfreund.github.io'>GitHub</a>. Erstellt mit <a href='http://jekyllrb.com'>Jekyll</a> und <a href='http://inuitcss.com'>inuitcss</a>. Und das notwendige <a href='/de/impressum/'>Impressum</a>."

  en:
    url: "/en/"
    language: "en"
    nav:
    - text: "Blog"
      url:  "/en/"
      class: "site-nav__item--blog"
    - text: "Portfolio"
      url:  "/en/portfolio/"
      class: "site-nav__item--portfolio"
    - text: "Profile"
      url:  "/en/profile/"
      class: "site-nav__item--profile"
    description: "Moonbase of Philipp Rudloff. Doing Web Development and Design. Things and stuff."
    footer: "Moonbase of <a href='http://twitter.com/kleinfreund'>Philipp Rudloff</a>. Source code hosted on <a href='http://github.com/kleinfreund/kleinfreund.github.io'>GitHub</a>. Built with <a href='http://jekyllrb.com'>Jekyll</a> and <a href='http://inuitcss.com'>inuitcss</a>. And the necessary <a href='/en/legal-disclosure/'>legal disclosure</a>."
