name: kleinfreund
title: kleinfreund.de
url: https://kleinfreund.de
description: 'Moonbase of Philipp Rudloff. About (front-end) development and design, music and various other things that cross my mind.'

permalink: /:categories/:year/:month/:title

max_posts: 13

exclude:
  - 'node_modules'
  - '*.sublime-workspace'

plugins:
  - jekyll-sitemap

kramdown:
  input: GFM
  auto_ids: false

sass:
  style: compressed



ui_color: c14444

# Author information
author:
  name: Philipp Rudloff
  email: phrudloff@gmail.com
  twitter: https://twitter.com/kleinfreund
  github: https://github.com/kleinfreund
  flickr: https://www.flickr.com/photos/kleinfreund
  stackoverflow: http://stackoverflow.com/users/2036825
  codereview: http://codereview.stackexchange.com/users/35408
  bandcamp: https://bandcamp.com/kleinfreund
  bandcamp_wishlist: "https://bandcamp.com/kleinfreund#wishlist"

# compress.html by Anatol Broder (http://jch.penibelst.de)
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  ignore:
    envs: [development]


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "drafts"
    values:
      layout: "post"
