name: kleinfreund
title: hey.kleinfreund.de
url: http://hey.kleinfreund.de

permalink: /:categories/:year/:month/:title

max_posts: 10

gems:
  - jekyll-sitemap

kramdown:
  input: GFM
  auto_ids: false

sass:
  style: compressed



# Asset paths
assets:
  css: /css/
  sass: /sass/
  fonts: /fonts/
  images: /img/
  javascript: /js/

loadCSS_js: true

ui_color: 5e85d6

# Author information
author:
  name: Philipp Rudloff
  email: phrudloff@gmail.com
  twitter: https://twitter.com/kleinfreund
  github: https://github.com/kleinfreund
  flickr: https://www.flickr.com/photos/kleinfreund
  stackoverflow: http://stackoverflow.com/users/2036825
  codereview: http://codereview.stackexchange.com/users/35408
  bandcamp: https://bandcamp.com/kleinfreund

google_verify: 2D5zbZ2Vatb8CeFj1cUCRdJZ3SQatSUlQesml02jEPo

# compress.html by Anatol Broder (http://jch.penibelst.de)
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  ignore:
    envs: [local]



defaults:
  -
    values:
      layout: "default"
      lang: "de"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "en/_posts"
      type: "posts"
    values:
      lang: "en"
