name: kleinfreund
title: kleinfreund.de
url: http://kleinfreund.de

permalink: /:categories/:year/:month/:title
relative_permalinks: false

max_posts: 10

gems:
  - jekyll-sitemap

kramdown:
  input: GFM
  auto_ids: false

# Asset paths
path:
  css: css/
  sass: sass/
  fonts: fonts/
  images: img/
  javascript: js/

ui_color: 5e85d6

# Author information
author:
  name: Philipp Rudloff
  email: phrudloff@gmail.com
  twitter: https://twitter.com/kleinfreund
  github: https://github.com/kleinfreund
  flickr: https://www.flickr.com/photos/kleinfreund
  stackoverflow: http://stackoverflow.com/users/2036825
  codereview: http://codereview.stackexchange.com/users/35408

# google_analytics: UA-52540063-1
google_verify: 2D5zbZ2Vatb8CeFj1cUCRdJZ3SQatSUlQesml02jEPo

# https://github.com/penibelst/jekyll-compress-html by Anatol Broder
compress_html:
  clippings: [html, head, title, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  comments: ["<!--", "-->"]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]

defaults:
  # Default layout and language to everything
  -
    values:
      layout: "default"
      lang: "de"
  # Specify default pages’ layout
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  # Specify default posts’ layout
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  # Set language for everything inside `/en`
  -
    scope:
      path: "en"
    values:
      lang: "en"
  # Set language for English posts
  -
    scope:
      path: "en/_posts"
      type: "posts"
    values:
      lang: "en"
