baseURL: https://kleinfreund.de/
title: kleinfreund.de
languageCode: en-us

permalinks:
  post: /:title
paginate: 5

disableHugoGeneratorInject: true

smartypants: false
fractions: false
latexDashes: false
